# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'File_generator_UI.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QHeaderView, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTableWidget, QTableWidgetItem, QTextEdit,
    QWidget)

class Ui_File_generator_ui(object):
    def setupUi(self, File_generator_ui):
        if not File_generator_ui.objectName():
            File_generator_ui.setObjectName(u"File_generator_ui")
        File_generator_ui.resize(526, 635)
        self.textEdit_text = QTextEdit(File_generator_ui)
        self.textEdit_text.setObjectName(u"textEdit_text")
        self.textEdit_text.setGeometry(QRect(20, 20, 491, 251))
        self.textEdit_text.setReadOnly(True)
        self.comboBox_port_generic = QComboBox(File_generator_ui)
        self.comboBox_port_generic.addItem("")
        self.comboBox_port_generic.addItem("")
        self.comboBox_port_generic.setObjectName(u"comboBox_port_generic")
        self.comboBox_port_generic.setGeometry(QRect(10, 540, 91, 25))
        self.lineEdit_name = QLineEdit(File_generator_ui)
        self.lineEdit_name.setObjectName(u"lineEdit_name")
        self.lineEdit_name.setGeometry(QRect(110, 540, 91, 25))
        self.lineEdit_name.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.comboBox_type = QComboBox(File_generator_ui)
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.addItem("")
        self.comboBox_type.setObjectName(u"comboBox_type")
        self.comboBox_type.setGeometry(QRect(290, 540, 101, 25))
        self.lineEdit_bits = QLineEdit(File_generator_ui)
        self.lineEdit_bits.setObjectName(u"lineEdit_bits")
        self.lineEdit_bits.setGeometry(QRect(402, 540, 31, 25))
        self.lineEdit_bits.setLayoutDirection(Qt.LeftToRight)
        self.lineEdit_bits.setAutoFillBackground(False)
        self.lineEdit_bits.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.pushButton_add = QPushButton(File_generator_ui)
        self.pushButton_add.setObjectName(u"pushButton_add")
        self.pushButton_add.setGeometry(QRect(440, 540, 80, 25))
        self.pushButton_create = QPushButton(File_generator_ui)
        self.pushButton_create.setObjectName(u"pushButton_create")
        self.pushButton_create.setGeometry(QRect(340, 600, 80, 25))
        self.pushButton_cancel = QPushButton(File_generator_ui)
        self.pushButton_cancel.setObjectName(u"pushButton_cancel")
        self.pushButton_cancel.setGeometry(QRect(430, 600, 80, 25))
        self.pushButton_config = QPushButton(File_generator_ui)
        self.pushButton_config.setObjectName(u"pushButton_config")
        self.pushButton_config.setGeometry(QRect(250, 600, 80, 25))
        self.lineEdit_entity = QLineEdit(File_generator_ui)
        self.lineEdit_entity.setObjectName(u"lineEdit_entity")
        self.lineEdit_entity.setGeometry(QRect(100, 280, 91, 25))
        self.lineEdit_architecture = QLineEdit(File_generator_ui)
        self.lineEdit_architecture.setObjectName(u"lineEdit_architecture")
        self.lineEdit_architecture.setGeometry(QRect(320, 280, 111, 25))
        self.lineEdit_architecture.setReadOnly(True)
        self.comboBox_inout = QComboBox(File_generator_ui)
        self.comboBox_inout.addItem("")
        self.comboBox_inout.addItem("")
        self.comboBox_inout.addItem("")
        self.comboBox_inout.setObjectName(u"comboBox_inout")
        self.comboBox_inout.setGeometry(QRect(210, 540, 71, 25))
        self.tableWidget_content = QTableWidget(File_generator_ui)
        self.tableWidget_content.setObjectName(u"tableWidget_content")
        self.tableWidget_content.setGeometry(QRect(20, 310, 491, 201))
        self.label = QLabel(File_generator_ui)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 520, 71, 19))
        font = QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label_2 = QLabel(File_generator_ui)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(140, 520, 41, 19))
        self.label_2.setFont(font)
        self.label_inout = QLabel(File_generator_ui)
        self.label_inout.setObjectName(u"label_inout")
        self.label_inout.setGeometry(QRect(210, 520, 71, 19))
        self.label_inout.setFont(font)
        self.label_4 = QLabel(File_generator_ui)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(330, 520, 71, 19))
        self.label_4.setFont(font)
        self.label_5 = QLabel(File_generator_ui)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(400, 520, 71, 19))
        self.label_5.setFont(font)
        self.lineEdit_comment = QLineEdit(File_generator_ui)
        self.lineEdit_comment.setObjectName(u"lineEdit_comment")
        self.lineEdit_comment.setGeometry(QRect(110, 570, 321, 25))
        self.label_3 = QLabel(File_generator_ui)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(50, 570, 61, 19))
        self.label_3.setFont(font)
        self.label_6 = QLabel(File_generator_ui)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 280, 81, 19))
        self.label_6.setFont(font)
        self.label_7 = QLabel(File_generator_ui)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(200, 280, 111, 19))
        self.label_7.setFont(font)
        self.checkBox_comments = QCheckBox(File_generator_ui)
        self.checkBox_comments.setObjectName(u"checkBox_comments")
        self.checkBox_comments.setGeometry(QRect(440, 280, 106, 25))
        self.checkBox_comments.setFont(font)
        self.pushButton_components = QPushButton(File_generator_ui)
        self.pushButton_components.setObjectName(u"pushButton_components")
        self.pushButton_components.setGeometry(QRect(159, 600, 81, 27))
        self.tableWidget_content.raise_()
        self.textEdit_text.raise_()
        self.comboBox_port_generic.raise_()
        self.lineEdit_name.raise_()
        self.comboBox_type.raise_()
        self.lineEdit_bits.raise_()
        self.pushButton_add.raise_()
        self.pushButton_create.raise_()
        self.pushButton_cancel.raise_()
        self.pushButton_config.raise_()
        self.lineEdit_entity.raise_()
        self.lineEdit_architecture.raise_()
        self.comboBox_inout.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_inout.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.lineEdit_comment.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.checkBox_comments.raise_()
        self.pushButton_components.raise_()

        self.retranslateUi(File_generator_ui)

        QMetaObject.connectSlotsByName(File_generator_ui)
    # setupUi

    def retranslateUi(self, File_generator_ui):
        File_generator_ui.setWindowTitle(QCoreApplication.translate("File_generator_ui", u"Dialog", None))
        self.comboBox_port_generic.setItemText(0, QCoreApplication.translate("File_generator_ui", u"port", None))
        self.comboBox_port_generic.setItemText(1, QCoreApplication.translate("File_generator_ui", u"generic", None))

        self.lineEdit_name.setText("")
        self.comboBox_type.setItemText(0, QCoreApplication.translate("File_generator_ui", u"std_logic", None))
        self.comboBox_type.setItemText(1, QCoreApplication.translate("File_generator_ui", u"unsigned", None))
        self.comboBox_type.setItemText(2, QCoreApplication.translate("File_generator_ui", u"integer", None))
        self.comboBox_type.setItemText(3, QCoreApplication.translate("File_generator_ui", u"std_ulogic", None))

        self.lineEdit_bits.setText("")
        self.pushButton_add.setText(QCoreApplication.translate("File_generator_ui", u"Add", None))
        self.pushButton_create.setText(QCoreApplication.translate("File_generator_ui", u"Create", None))
        self.pushButton_cancel.setText(QCoreApplication.translate("File_generator_ui", u"Cancel", None))
        self.pushButton_config.setText(QCoreApplication.translate("File_generator_ui", u"Config", None))
        self.lineEdit_entity.setText("")
        self.lineEdit_architecture.setText("")
        self.comboBox_inout.setItemText(0, QCoreApplication.translate("File_generator_ui", u"in", None))
        self.comboBox_inout.setItemText(1, QCoreApplication.translate("File_generator_ui", u"out", None))
        self.comboBox_inout.setItemText(2, QCoreApplication.translate("File_generator_ui", u"inout", None))

        self.label.setText(QCoreApplication.translate("File_generator_ui", u"port/generic", None))
        self.label_2.setText(QCoreApplication.translate("File_generator_ui", u"name", None))
        self.label_inout.setText(QCoreApplication.translate("File_generator_ui", u"in/out/inout", None))
        self.label_4.setText(QCoreApplication.translate("File_generator_ui", u"type", None))
        self.label_5.setText(QCoreApplication.translate("File_generator_ui", u"N\u00ba bits", None))
        self.lineEdit_comment.setText("")
        self.label_3.setText(QCoreApplication.translate("File_generator_ui", u"comment", None))
        self.label_6.setText(QCoreApplication.translate("File_generator_ui", u"entity name:", None))
        self.label_7.setText(QCoreApplication.translate("File_generator_ui", u"architecture name:", None))
        self.checkBox_comments.setText(QCoreApplication.translate("File_generator_ui", u"comments", None))
        self.pushButton_components.setText(QCoreApplication.translate("File_generator_ui", u"add files", None))
    # retranslateUi

