# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HDLHelper_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HDLHelper(object):
    def setupUi(self, HDLHelper):
        HDLHelper.setObjectName("HDLHelper")
        HDLHelper.resize(639, 760)
        self.horizontalLayoutWidget = QtWidgets.QWidget(HDLHelper)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 541, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.testbench_generator_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.testbench_generator_button.setObjectName("testbench_generator_button")
        self.horizontalLayout.addWidget(self.testbench_generator_button)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.calculator_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.calculator_button.setObjectName("calculator_button")
        self.horizontalLayout.addWidget(self.calculator_button)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.top_file_generator_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.top_file_generator_button.setObjectName("top_file_generator_button")
        self.horizontalLayout.addWidget(self.top_file_generator_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(HDLHelper)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 140, 541, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ticks_calculator_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.ticks_calculator_button.setObjectName("ticks_calculator_button")
        self.horizontalLayout_2.addWidget(self.ticks_calculator_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.hdl_translator_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.hdl_translator_button.setObjectName("hdl_translator_button")
        self.horizontalLayout_2.addWidget(self.hdl_translator_button)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.hdl_generator_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.hdl_generator_button.setObjectName("hdl_generator_button")
        self.horizontalLayout_2.addWidget(self.hdl_generator_button)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(HDLHelper)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(50, 240, 546, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.editor_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.editor_button.setObjectName("editor_button")
        self.horizontalLayout_3.addWidget(self.editor_button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.documentation_generator_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.documentation_generator_button.setObjectName("documentation_generator_button")
        self.horizontalLayout_3.addWidget(self.documentation_generator_button)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.analize_dependencies_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.analize_dependencies_button.setObjectName("analize_dependencies_button")
        self.horizontalLayout_3.addWidget(self.analize_dependencies_button)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(HDLHelper)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(50, 340, 541, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.generate_state_machine_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.generate_state_machine_button.setObjectName("generate_state_machine_button")
        self.horizontalLayout_4.addWidget(self.generate_state_machine_button)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.ascii_conversor_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ascii_conversor_button.setEnabled(True)
        self.ascii_conversor_button.setObjectName("ascii_conversor_button")
        self.horizontalLayout_4.addWidget(self.ascii_conversor_button)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.auto_improve_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.auto_improve_button.setEnabled(True)
        self.auto_improve_button.setObjectName("auto_improve_button")
        self.horizontalLayout_4.addWidget(self.auto_improve_button)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(HDLHelper)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(50, 440, 541, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.axi_generator_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.axi_generator_button.setObjectName("axi_generator_button")
        self.horizontalLayout_5.addWidget(self.axi_generator_button)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.shape_generator_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.shape_generator_button.setEnabled(True)
        self.shape_generator_button.setObjectName("shape_generator_button")
        self.horizontalLayout_5.addWidget(self.shape_generator_button)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.antirrebotes_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.antirrebotes_button.setEnabled(True)
        self.antirrebotes_button.setObjectName("antirrebotes_button")
        self.horizontalLayout_5.addWidget(self.antirrebotes_button)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(HDLHelper)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(50, 540, 541, 80))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.clock_divisor_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.clock_divisor_button.setObjectName("clock_divisor_button")
        self.horizontalLayout_6.addWidget(self.clock_divisor_button)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.filter_generator_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.filter_generator_button.setEnabled(True)
        self.filter_generator_button.setObjectName("filter_generator_button")
        self.horizontalLayout_6.addWidget(self.filter_generator_button)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.auto_improve_button_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.auto_improve_button_3.setEnabled(True)
        self.auto_improve_button_3.setText("")
        self.auto_improve_button_3.setObjectName("auto_improve_button_3")
        self.horizontalLayout_6.addWidget(self.auto_improve_button_3)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(HDLHelper)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(50, 640, 541, 80))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.clock_divisor_button_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.clock_divisor_button_2.setObjectName("clock_divisor_button_2")
        self.horizontalLayout_7.addWidget(self.clock_divisor_button_2)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.filter_generator_button_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.filter_generator_button_2.setEnabled(True)
        self.filter_generator_button_2.setObjectName("filter_generator_button_2")
        self.horizontalLayout_7.addWidget(self.filter_generator_button_2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.auto_improve_button_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.auto_improve_button_4.setEnabled(True)
        self.auto_improve_button_4.setObjectName("auto_improve_button_4")
        self.horizontalLayout_7.addWidget(self.auto_improve_button_4)

        self.retranslateUi(HDLHelper)
        QtCore.QMetaObject.connectSlotsByName(HDLHelper)

    def retranslateUi(self, HDLHelper):
        _translate = QtCore.QCoreApplication.translate
        HDLHelper.setWindowTitle(_translate("HDLHelper", "Dialog"))
        self.testbench_generator_button.setText(_translate("HDLHelper", "Testbench generator"))
        self.calculator_button.setText(_translate("HDLHelper", "Calculator"))
        self.top_file_generator_button.setText(_translate("HDLHelper", "Top file generator"))
        self.ticks_calculator_button.setText(_translate("HDLHelper", "Ticks calculator"))
        self.hdl_translator_button.setText(_translate("HDLHelper", ".v <-> .vhd"))
        self.hdl_generator_button.setText(_translate("HDLHelper", "HDL generator"))
        self.editor_button.setText(_translate("HDLHelper", "Editor"))
        self.documentation_generator_button.setText(_translate("HDLHelper", "Documentation generator"))
        self.analize_dependencies_button.setText(_translate("HDLHelper", "Analize dependencies"))
        self.generate_state_machine_button.setText(_translate("HDLHelper", "Gen. State Machine"))
        self.ascii_conversor_button.setText(_translate("HDLHelper", "ASCII Conversor"))
        self.auto_improve_button.setText(_translate("HDLHelper", "Reshape code"))
        self.axi_generator_button.setText(_translate("HDLHelper", "AXI generator"))
        self.shape_generator_button.setText(_translate("HDLHelper", "Shapes generator"))
        self.antirrebotes_button.setText(_translate("HDLHelper", "Debounce"))
        self.clock_divisor_button.setText(_translate("HDLHelper", "Prescaler clock"))
        self.filter_generator_button.setText(_translate("HDLHelper", "Filter generator"))
        self.clock_divisor_button_2.setText(_translate("HDLHelper", "Control Engineering"))
        self.filter_generator_button_2.setText(_translate("HDLHelper", "Power Control"))
        self.auto_improve_button_4.setText(_translate("HDLHelper", "Communication"))
