# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HDLHelper.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HDLHelper(object):
    def setupUi(self, HDLHelper):
        HDLHelper.setObjectName("HDLHelper")
        HDLHelper.resize(639, 462)
        self.horizontalLayoutWidget = QtWidgets.QWidget(HDLHelper)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 541, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(HDLHelper)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 140, 541, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.retranslateUi(HDLHelper)
        QtCore.QMetaObject.connectSlotsByName(HDLHelper)

    def retranslateUi(self, HDLHelper):
        _translate = QtCore.QCoreApplication.translate
        HDLHelper.setWindowTitle(_translate("HDLHelper", "Dialog"))
        self.pushButton_4.setText(_translate("HDLHelper", "Testbench generator"))
        self.pushButton_3.setText(_translate("HDLHelper", "Calculator"))
        self.pushButton.setText(_translate("HDLHelper", "Top file generator"))
