# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pulse_calculator_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pulses_calculator(object):
    def setupUi(self, Pulses_calculator):
        Pulses_calculator.setObjectName("Pulses_calculator")
        Pulses_calculator.resize(589, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Pulses_calculator.sizePolicy().hasHeightForWidth())
        Pulses_calculator.setSizePolicy(sizePolicy)
        self.lineEdit = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit.setGeometry(QtCore.QRect(70, 110, 91, 36))
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 180, 91, 36))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.comboBox = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox.setGeometry(QtCore.QRect(180, 110, 81, 36))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Pulses_calculator)
        self.label.setGeometry(QtCore.QRect(280, 120, 21, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Pulses_calculator)
        self.label_2.setGeometry(QtCore.QRect(280, 190, 21, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton.setGeometry(QtCore.QRect(470, 290, 95, 36))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 290, 95, 36))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(Pulses_calculator)
        self.label_4.setGeometry(QtCore.QRect(370, 40, 71, 17))
        self.label_4.setObjectName("label_4")
        self.radioButton = QtWidgets.QRadioButton(Pulses_calculator)
        self.radioButton.setGeometry(QtCore.QRect(120, 30, 104, 23))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Pulses_calculator)
        self.radioButton_2.setGeometry(QtCore.QRect(120, 60, 104, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.comboBox_2 = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 180, 81, 36))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_4.setGeometry(QtCore.QRect(440, 110, 81, 36))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_5.setGeometry(QtCore.QRect(330, 180, 91, 36))
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 110, 91, 36))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox_5 = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_5.setGeometry(QtCore.QRect(440, 180, 81, 36))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_5 = QtWidgets.QLabel(Pulses_calculator)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 31, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Pulses_calculator)
        self.label_6.setGeometry(QtCore.QRect(30, 260, 31, 17))
        self.label_6.setObjectName("label_6")
        self.binary_result = QtWidgets.QLabel(Pulses_calculator)
        self.binary_result.setGeometry(QtCore.QRect(70, 230, 141, 17))
        self.binary_result.setText("")
        self.binary_result.setObjectName("binary_result")
        self.hexadecimal_result = QtWidgets.QLabel(Pulses_calculator)
        self.hexadecimal_result.setGeometry(QtCore.QRect(70, 260, 141, 17))
        self.hexadecimal_result.setText("")
        self.hexadecimal_result.setObjectName("hexadecimal_result")

        self.retranslateUi(Pulses_calculator)
        QtCore.QMetaObject.connectSlotsByName(Pulses_calculator)

    def retranslateUi(self, Pulses_calculator):
        _translate = QtCore.QCoreApplication.translate
        Pulses_calculator.setWindowTitle(_translate("Pulses_calculator", "Dialog"))
        self.comboBox.setCurrentText(_translate("Pulses_calculator", "MHz"))
        self.comboBox.setItemText(0, _translate("Pulses_calculator", "MHz"))
        self.comboBox.setItemText(1, _translate("Pulses_calculator", "Hz"))
        self.comboBox.setItemText(2, _translate("Pulses_calculator", "kHz"))
        self.comboBox.setItemText(3, _translate("Pulses_calculator", "GHz"))
        self.label.setText(_translate("Pulses_calculator", "<-->"))
        self.label_2.setText(_translate("Pulses_calculator", "<-->"))
        self.pushButton.setText(_translate("Pulses_calculator", "Calculate"))
        self.pushButton_2.setText(_translate("Pulses_calculator", "Cancel"))
        self.label_4.setText(_translate("Pulses_calculator", "Seconds"))
        self.radioButton.setText(_translate("Pulses_calculator", "Frequency"))
        self.radioButton_2.setText(_translate("Pulses_calculator", "Pulses"))
        self.comboBox_2.setItemText(0, _translate("Pulses_calculator", "Hz"))
        self.comboBox_2.setItemText(1, _translate("Pulses_calculator", "kHz"))
        self.comboBox_2.setItemText(2, _translate("Pulses_calculator", "MHz"))
        self.comboBox_2.setItemText(3, _translate("Pulses_calculator", "GHz"))
        self.comboBox_4.setItemText(0, _translate("Pulses_calculator", "sec"))
        self.comboBox_4.setItemText(1, _translate("Pulses_calculator", "msec"))
        self.comboBox_4.setItemText(2, _translate("Pulses_calculator", "usec"))
        self.comboBox_4.setItemText(3, _translate("Pulses_calculator", "nsec"))
        self.comboBox_5.setItemText(0, _translate("Pulses_calculator", "sec"))
        self.comboBox_5.setItemText(1, _translate("Pulses_calculator", "msec"))
        self.comboBox_5.setItemText(2, _translate("Pulses_calculator", "usec"))
        self.comboBox_5.setItemText(3, _translate("Pulses_calculator", "nsec"))
        self.label_5.setText(_translate("Pulses_calculator", "Bin:"))
        self.label_6.setText(_translate("Pulses_calculator", "Hex:"))
