# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pulse_calculator_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pulses_calculator(object):
    def setupUi(self, Pulses_calculator):
        Pulses_calculator.setObjectName("Pulses_calculator")
        Pulses_calculator.resize(589, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Pulses_calculator.sizePolicy().hasHeightForWidth())
        Pulses_calculator.setSizePolicy(sizePolicy)
        self.lineEdit_f_p_global = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_f_p_global.setGeometry(QtCore.QRect(70, 110, 91, 36))
        self.lineEdit_f_p_global.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_f_p_global.setObjectName("lineEdit_f_p_global")
        self.lineEdit_f_p_local = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_f_p_local.setGeometry(QtCore.QRect(70, 180, 91, 36))
        self.lineEdit_f_p_local.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_f_p_local.setObjectName("lineEdit_f_p_local")
        self.comboBox_f_p_general = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_f_p_general.setGeometry(QtCore.QRect(180, 110, 81, 36))
        self.comboBox_f_p_general.setObjectName("comboBox_f_p_general")
        self.comboBox_f_p_general.addItem("")
        self.comboBox_f_p_general.addItem("")
        self.comboBox_f_p_general.addItem("")
        self.comboBox_f_p_general.addItem("")
        self.label = QtWidgets.QLabel(Pulses_calculator)
        self.label.setGeometry(QtCore.QRect(280, 120, 41, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Pulses_calculator)
        self.label_2.setGeometry(QtCore.QRect(280, 190, 41, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton_calculate = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_calculate.setGeometry(QtCore.QRect(470, 290, 95, 36))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.pushButton_cancel = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_cancel.setGeometry(QtCore.QRect(350, 290, 95, 36))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_4 = QtWidgets.QLabel(Pulses_calculator)
        self.label_4.setGeometry(QtCore.QRect(370, 40, 71, 17))
        self.label_4.setObjectName("label_4")
        self.radioButton_frequency = QtWidgets.QRadioButton(Pulses_calculator)
        self.radioButton_frequency.setGeometry(QtCore.QRect(120, 30, 104, 23))
        self.radioButton_frequency.setChecked(True)
        self.radioButton_frequency.setObjectName("radioButton_frequency")
        self.radioButton_pulses = QtWidgets.QRadioButton(Pulses_calculator)
        self.radioButton_pulses.setGeometry(QtCore.QRect(120, 60, 104, 23))
        self.radioButton_pulses.setObjectName("radioButton_pulses")
        self.comboBox_f_p_local = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_f_p_local.setGeometry(QtCore.QRect(180, 180, 81, 36))
        self.comboBox_f_p_local.setObjectName("comboBox_f_p_local")
        self.comboBox_f_p_local.addItem("")
        self.comboBox_f_p_local.addItem("")
        self.comboBox_f_p_local.addItem("")
        self.comboBox_f_p_local.addItem("")
        self.comboBox_seconds_general = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_seconds_general.setGeometry(QtCore.QRect(440, 110, 81, 36))
        self.comboBox_seconds_general.setObjectName("comboBox_seconds_general")
        self.comboBox_seconds_general.addItem("")
        self.comboBox_seconds_general.addItem("")
        self.comboBox_seconds_general.addItem("")
        self.comboBox_seconds_general.addItem("")
        self.lineEdit_seconds_local = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_seconds_local.setGeometry(QtCore.QRect(330, 180, 91, 36))
        self.lineEdit_seconds_local.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_seconds_local.setObjectName("lineEdit_seconds_local")
        self.lineEdit_seconds_general = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_seconds_general.setGeometry(QtCore.QRect(330, 110, 91, 36))
        self.lineEdit_seconds_general.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_seconds_general.setObjectName("lineEdit_seconds_general")
        self.comboBox_seconds_local = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_seconds_local.setGeometry(QtCore.QRect(440, 180, 81, 36))
        self.comboBox_seconds_local.setObjectName("comboBox_seconds_local")
        self.comboBox_seconds_local.addItem("")
        self.comboBox_seconds_local.addItem("")
        self.comboBox_seconds_local.addItem("")
        self.comboBox_seconds_local.addItem("")
        self.label_5 = QtWidgets.QLabel(Pulses_calculator)
        self.label_5.setGeometry(QtCore.QRect(30, 230, 31, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Pulses_calculator)
        self.label_6.setGeometry(QtCore.QRect(30, 260, 41, 17))
        self.label_6.setObjectName("label_6")
        self.binary_result = QtWidgets.QLabel(Pulses_calculator)
        self.binary_result.setGeometry(QtCore.QRect(70, 230, 141, 17))
        self.binary_result.setText("")
        self.binary_result.setObjectName("binary_result")
        self.hexadecimal_result = QtWidgets.QLabel(Pulses_calculator)
        self.hexadecimal_result.setGeometry(QtCore.QRect(70, 260, 141, 17))
        self.hexadecimal_result.setText("")
        self.hexadecimal_result.setObjectName("hexadecimal_result")

        self.retranslateUi(Pulses_calculator)
        QtCore.QMetaObject.connectSlotsByName(Pulses_calculator)

    def retranslateUi(self, Pulses_calculator):
        _translate = QtCore.QCoreApplication.translate
        Pulses_calculator.setWindowTitle(_translate("Pulses_calculator", "Pulses_calculator"))
        self.comboBox_f_p_general.setCurrentText(_translate("Pulses_calculator", "MHz"))
        self.comboBox_f_p_general.setItemText(0, _translate("Pulses_calculator", "MHz"))
        self.comboBox_f_p_general.setItemText(1, _translate("Pulses_calculator", "Hz"))
        self.comboBox_f_p_general.setItemText(2, _translate("Pulses_calculator", "kHz"))
        self.comboBox_f_p_general.setItemText(3, _translate("Pulses_calculator", "GHz"))
        self.label.setText(_translate("Pulses_calculator", "<-->"))
        self.label_2.setText(_translate("Pulses_calculator", "<-->"))
        self.pushButton_calculate.setText(_translate("Pulses_calculator", "Calculate"))
        self.pushButton_cancel.setText(_translate("Pulses_calculator", "Cancel"))
        self.label_4.setText(_translate("Pulses_calculator", "Seconds"))
        self.radioButton_frequency.setText(_translate("Pulses_calculator", "Frequency"))
        self.radioButton_pulses.setText(_translate("Pulses_calculator", "Pulses"))
        self.comboBox_f_p_local.setItemText(0, _translate("Pulses_calculator", "Hz"))
        self.comboBox_f_p_local.setItemText(1, _translate("Pulses_calculator", "kHz"))
        self.comboBox_f_p_local.setItemText(2, _translate("Pulses_calculator", "MHz"))
        self.comboBox_f_p_local.setItemText(3, _translate("Pulses_calculator", "GHz"))
        self.comboBox_seconds_general.setItemText(0, _translate("Pulses_calculator", "sec"))
        self.comboBox_seconds_general.setItemText(1, _translate("Pulses_calculator", "msec"))
        self.comboBox_seconds_general.setItemText(2, _translate("Pulses_calculator", "usec"))
        self.comboBox_seconds_general.setItemText(3, _translate("Pulses_calculator", "nsec"))
        self.comboBox_seconds_local.setItemText(0, _translate("Pulses_calculator", "sec"))
        self.comboBox_seconds_local.setItemText(1, _translate("Pulses_calculator", "msec"))
        self.comboBox_seconds_local.setItemText(2, _translate("Pulses_calculator", "usec"))
        self.comboBox_seconds_local.setItemText(3, _translate("Pulses_calculator", "nsec"))
        self.label_5.setText(_translate("Pulses_calculator", "Bin:"))
        self.label_6.setText(_translate("Pulses_calculator", "Hex:"))
