# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pulse_calculator_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pulses_calculator(object):
    def setupUi(self, Pulses_calculator):
        Pulses_calculator.setObjectName("Pulses_calculator")
        Pulses_calculator.resize(589, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Pulses_calculator.sizePolicy().hasHeightForWidth())
        Pulses_calculator.setSizePolicy(sizePolicy)
        self.lineEdit_var1 = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_var1.setGeometry(QtCore.QRect(70, 110, 91, 31))
        self.lineEdit_var1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_var1.setObjectName("lineEdit_var1")
        self.lineEdit_var3 = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_var3.setGeometry(QtCore.QRect(70, 180, 91, 31))
        self.lineEdit_var3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_var3.setObjectName("lineEdit_var3")
        self.comboBox_var1 = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_var1.setGeometry(QtCore.QRect(180, 110, 81, 31))
        self.comboBox_var1.setObjectName("comboBox_var1")
        self.comboBox_var1.addItem("")
        self.comboBox_var1.addItem("")
        self.comboBox_var1.addItem("")
        self.comboBox_var1.addItem("")
        self.label = QtWidgets.QLabel(Pulses_calculator)
        self.label.setGeometry(QtCore.QRect(280, 115, 41, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Pulses_calculator)
        self.label_2.setGeometry(QtCore.QRect(280, 185, 41, 17))
        self.label_2.setObjectName("label_2")
        self.pushButton_calculate = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_calculate.setGeometry(QtCore.QRect(470, 290, 95, 36))
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.pushButton_cancel = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_cancel.setGeometry(QtCore.QRect(350, 290, 95, 36))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label_4 = QtWidgets.QLabel(Pulses_calculator)
        self.label_4.setGeometry(QtCore.QRect(370, 40, 71, 17))
        self.label_4.setObjectName("label_4")
        self.radioButton_frequency = QtWidgets.QRadioButton(Pulses_calculator)
        self.radioButton_frequency.setGeometry(QtCore.QRect(120, 30, 104, 23))
        self.radioButton_frequency.setChecked(True)
        self.radioButton_frequency.setObjectName("radioButton_frequency")
        self.radioButton_pulses = QtWidgets.QRadioButton(Pulses_calculator)
        self.radioButton_pulses.setGeometry(QtCore.QRect(120, 60, 104, 23))
        self.radioButton_pulses.setObjectName("radioButton_pulses")
        self.comboBox_var3 = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_var3.setGeometry(QtCore.QRect(180, 180, 81, 31))
        self.comboBox_var3.setObjectName("comboBox_var3")
        self.comboBox_var3.addItem("")
        self.comboBox_var3.addItem("")
        self.comboBox_var3.addItem("")
        self.comboBox_var3.addItem("")
        self.comboBox_var2 = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_var2.setGeometry(QtCore.QRect(440, 110, 81, 31))
        self.comboBox_var2.setObjectName("comboBox_var2")
        self.comboBox_var2.addItem("")
        self.comboBox_var2.addItem("")
        self.comboBox_var2.addItem("")
        self.comboBox_var2.addItem("")
        self.lineEdit_var4 = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_var4.setGeometry(QtCore.QRect(330, 180, 91, 31))
        self.lineEdit_var4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_var4.setObjectName("lineEdit_var4")
        self.lineEdit_var2 = QtWidgets.QLineEdit(Pulses_calculator)
        self.lineEdit_var2.setGeometry(QtCore.QRect(330, 110, 91, 31))
        self.lineEdit_var2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_var2.setObjectName("lineEdit_var2")
        self.comboBox_var4 = QtWidgets.QComboBox(Pulses_calculator)
        self.comboBox_var4.setGeometry(QtCore.QRect(440, 180, 81, 31))
        self.comboBox_var4.setObjectName("comboBox_var4")
        self.comboBox_var4.addItem("")
        self.comboBox_var4.addItem("")
        self.comboBox_var4.addItem("")
        self.comboBox_var4.addItem("")
        self.label_binary_result = QtWidgets.QLabel(Pulses_calculator)
        self.label_binary_result.setGeometry(QtCore.QRect(110, 230, 461, 17))
        self.label_binary_result.setText("")
        self.label_binary_result.setObjectName("label_binary_result")
        self.label_hexadecimal_result = QtWidgets.QLabel(Pulses_calculator)
        self.label_hexadecimal_result.setGeometry(QtCore.QRect(110, 260, 461, 17))
        self.label_hexadecimal_result.setText("")
        self.label_hexadecimal_result.setObjectName("label_hexadecimal_result")
        self.label_error = QtWidgets.QLabel(Pulses_calculator)
        self.label_error.setGeometry(QtCore.QRect(220, 240, 331, 41))
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.pushButton_remove = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_remove.setGeometry(QtCore.QRect(230, 290, 95, 36))
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.pushButton_clean1 = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_clean1.setGeometry(QtCore.QRect(10, 110, 51, 31))
        self.pushButton_clean1.setObjectName("pushButton_clean1")
        self.pushButton_clean3 = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_clean3.setGeometry(QtCore.QRect(10, 180, 51, 31))
        self.pushButton_clean3.setObjectName("pushButton_clean3")
        self.pushButton_clean2 = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_clean2.setGeometry(QtCore.QRect(530, 110, 51, 31))
        self.pushButton_clean2.setObjectName("pushButton_clean2")
        self.pushButton_clean4 = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_clean4.setGeometry(QtCore.QRect(530, 180, 51, 31))
        self.pushButton_clean4.setObjectName("pushButton_clean4")
        self.pushButton_bin = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_bin.setGeometry(QtCore.QRect(30, 227, 71, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.pushButton_bin.setFont(font)
        self.pushButton_bin.setObjectName("pushButton_bin")
        self.pushButton_hex = QtWidgets.QPushButton(Pulses_calculator)
        self.pushButton_hex.setGeometry(QtCore.QRect(30, 260, 71, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.pushButton_hex.setFont(font)
        self.pushButton_hex.setObjectName("pushButton_hex")

        self.retranslateUi(Pulses_calculator)
        QtCore.QMetaObject.connectSlotsByName(Pulses_calculator)

    def retranslateUi(self, Pulses_calculator):
        _translate = QtCore.QCoreApplication.translate
        Pulses_calculator.setWindowTitle(_translate("Pulses_calculator", "Pulses_calculator"))
        self.comboBox_var1.setCurrentText(_translate("Pulses_calculator", "MHz"))
        self.comboBox_var1.setItemText(0, _translate("Pulses_calculator", "MHz"))
        self.comboBox_var1.setItemText(1, _translate("Pulses_calculator", "Hz"))
        self.comboBox_var1.setItemText(2, _translate("Pulses_calculator", "kHz"))
        self.comboBox_var1.setItemText(3, _translate("Pulses_calculator", "GHz"))
        self.label.setText(_translate("Pulses_calculator", "<-->"))
        self.label_2.setText(_translate("Pulses_calculator", "<-->"))
        self.pushButton_calculate.setText(_translate("Pulses_calculator", "Calculate"))
        self.pushButton_cancel.setText(_translate("Pulses_calculator", "Cancel"))
        self.label_4.setText(_translate("Pulses_calculator", "Seconds"))
        self.radioButton_frequency.setText(_translate("Pulses_calculator", "Frequency"))
        self.radioButton_pulses.setText(_translate("Pulses_calculator", "Pulses"))
        self.comboBox_var3.setItemText(0, _translate("Pulses_calculator", "Hz"))
        self.comboBox_var3.setItemText(1, _translate("Pulses_calculator", "kHz"))
        self.comboBox_var3.setItemText(2, _translate("Pulses_calculator", "MHz"))
        self.comboBox_var3.setItemText(3, _translate("Pulses_calculator", "GHz"))
        self.comboBox_var2.setItemText(0, _translate("Pulses_calculator", "sec"))
        self.comboBox_var2.setItemText(1, _translate("Pulses_calculator", "msec"))
        self.comboBox_var2.setItemText(2, _translate("Pulses_calculator", "usec"))
        self.comboBox_var2.setItemText(3, _translate("Pulses_calculator", "nsec"))
        self.comboBox_var4.setItemText(0, _translate("Pulses_calculator", "sec"))
        self.comboBox_var4.setItemText(1, _translate("Pulses_calculator", "msec"))
        self.comboBox_var4.setItemText(2, _translate("Pulses_calculator", "usec"))
        self.comboBox_var4.setItemText(3, _translate("Pulses_calculator", "nsec"))
        self.pushButton_remove.setText(_translate("Pulses_calculator", "Remove all"))
        self.pushButton_clean1.setText(_translate("Pulses_calculator", "clean"))
        self.pushButton_clean3.setText(_translate("Pulses_calculator", "clean"))
        self.pushButton_clean2.setText(_translate("Pulses_calculator", "clean"))
        self.pushButton_clean4.setText(_translate("Pulses_calculator", "clean"))
        self.pushButton_bin.setText(_translate("Pulses_calculator", "Bin"))
        self.pushButton_hex.setText(_translate("Pulses_calculator", "Hex"))
