# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Pulse_calculator_UI.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QLabel,
    QLineEdit, QPushButton, QRadioButton, QSizePolicy,
    QWidget)

class Ui_Pulses_calculator(object):
    def setupUi(self, Pulses_calculator):
        if not Pulses_calculator.objectName():
            Pulses_calculator.setObjectName(u"Pulses_calculator")
        Pulses_calculator.resize(589, 350)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Pulses_calculator.sizePolicy().hasHeightForWidth())
        Pulses_calculator.setSizePolicy(sizePolicy)
        self.lineEdit_var1 = QLineEdit(Pulses_calculator)
        self.lineEdit_var1.setObjectName(u"lineEdit_var1")
        self.lineEdit_var1.setGeometry(QRect(70, 110, 91, 31))
        self.lineEdit_var1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_var3 = QLineEdit(Pulses_calculator)
        self.lineEdit_var3.setObjectName(u"lineEdit_var3")
        self.lineEdit_var3.setGeometry(QRect(70, 180, 91, 31))
        self.lineEdit_var3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_var1 = QComboBox(Pulses_calculator)
        self.comboBox_var1.addItem("")
        self.comboBox_var1.addItem("")
        self.comboBox_var1.addItem("")
        self.comboBox_var1.addItem("")
        self.comboBox_var1.setObjectName(u"comboBox_var1")
        self.comboBox_var1.setGeometry(QRect(180, 110, 81, 31))
        self.label = QLabel(Pulses_calculator)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(280, 115, 41, 17))
        self.label_2 = QLabel(Pulses_calculator)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(280, 185, 41, 17))
        self.pushButton_calculate = QPushButton(Pulses_calculator)
        self.pushButton_calculate.setObjectName(u"pushButton_calculate")
        self.pushButton_calculate.setGeometry(QRect(470, 290, 95, 36))
        self.pushButton_cancel = QPushButton(Pulses_calculator)
        self.pushButton_cancel.setObjectName(u"pushButton_cancel")
        self.pushButton_cancel.setGeometry(QRect(350, 290, 95, 36))
        self.label_4 = QLabel(Pulses_calculator)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(370, 40, 71, 17))
        self.radioButton_frequency = QRadioButton(Pulses_calculator)
        self.radioButton_frequency.setObjectName(u"radioButton_frequency")
        self.radioButton_frequency.setGeometry(QRect(120, 30, 104, 23))
        self.radioButton_frequency.setChecked(True)
        self.radioButton_pulses = QRadioButton(Pulses_calculator)
        self.radioButton_pulses.setObjectName(u"radioButton_pulses")
        self.radioButton_pulses.setGeometry(QRect(120, 60, 104, 23))
        self.comboBox_var3 = QComboBox(Pulses_calculator)
        self.comboBox_var3.addItem("")
        self.comboBox_var3.addItem("")
        self.comboBox_var3.addItem("")
        self.comboBox_var3.addItem("")
        self.comboBox_var3.setObjectName(u"comboBox_var3")
        self.comboBox_var3.setGeometry(QRect(180, 180, 81, 31))
        self.comboBox_var2 = QComboBox(Pulses_calculator)
        self.comboBox_var2.addItem("")
        self.comboBox_var2.addItem("")
        self.comboBox_var2.addItem("")
        self.comboBox_var2.addItem("")
        self.comboBox_var2.setObjectName(u"comboBox_var2")
        self.comboBox_var2.setGeometry(QRect(440, 110, 81, 31))
        self.lineEdit_var4 = QLineEdit(Pulses_calculator)
        self.lineEdit_var4.setObjectName(u"lineEdit_var4")
        self.lineEdit_var4.setGeometry(QRect(330, 180, 91, 31))
        self.lineEdit_var4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineEdit_var2 = QLineEdit(Pulses_calculator)
        self.lineEdit_var2.setObjectName(u"lineEdit_var2")
        self.lineEdit_var2.setGeometry(QRect(330, 110, 91, 31))
        self.lineEdit_var2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.comboBox_var4 = QComboBox(Pulses_calculator)
        self.comboBox_var4.addItem("")
        self.comboBox_var4.addItem("")
        self.comboBox_var4.addItem("")
        self.comboBox_var4.addItem("")
        self.comboBox_var4.setObjectName(u"comboBox_var4")
        self.comboBox_var4.setGeometry(QRect(440, 180, 81, 31))
        self.label_binary_result = QLabel(Pulses_calculator)
        self.label_binary_result.setObjectName(u"label_binary_result")
        self.label_binary_result.setGeometry(QRect(110, 230, 461, 17))
        self.label_hexadecimal_result = QLabel(Pulses_calculator)
        self.label_hexadecimal_result.setObjectName(u"label_hexadecimal_result")
        self.label_hexadecimal_result.setGeometry(QRect(110, 260, 461, 17))
        self.label_error = QLabel(Pulses_calculator)
        self.label_error.setObjectName(u"label_error")
        self.label_error.setGeometry(QRect(220, 240, 331, 41))
        self.pushButton_remove = QPushButton(Pulses_calculator)
        self.pushButton_remove.setObjectName(u"pushButton_remove")
        self.pushButton_remove.setGeometry(QRect(230, 290, 95, 36))
        self.pushButton_clean1 = QPushButton(Pulses_calculator)
        self.pushButton_clean1.setObjectName(u"pushButton_clean1")
        self.pushButton_clean1.setGeometry(QRect(10, 110, 51, 31))
        self.pushButton_clean3 = QPushButton(Pulses_calculator)
        self.pushButton_clean3.setObjectName(u"pushButton_clean3")
        self.pushButton_clean3.setGeometry(QRect(10, 180, 51, 31))
        self.pushButton_clean2 = QPushButton(Pulses_calculator)
        self.pushButton_clean2.setObjectName(u"pushButton_clean2")
        self.pushButton_clean2.setGeometry(QRect(530, 110, 51, 31))
        self.pushButton_clean4 = QPushButton(Pulses_calculator)
        self.pushButton_clean4.setObjectName(u"pushButton_clean4")
        self.pushButton_clean4.setGeometry(QRect(530, 180, 51, 31))
        self.pushButton_bin = QPushButton(Pulses_calculator)
        self.pushButton_bin.setObjectName(u"pushButton_bin")
        self.pushButton_bin.setGeometry(QRect(30, 227, 71, 20))
        font = QFont()
        font.setItalic(False)
        self.pushButton_bin.setFont(font)
        self.pushButton_hex = QPushButton(Pulses_calculator)
        self.pushButton_hex.setObjectName(u"pushButton_hex")
        self.pushButton_hex.setGeometry(QRect(30, 260, 71, 20))
        self.pushButton_hex.setFont(font)

        self.retranslateUi(Pulses_calculator)

        QMetaObject.connectSlotsByName(Pulses_calculator)
    # setupUi

    def retranslateUi(self, Pulses_calculator):
        Pulses_calculator.setWindowTitle(QCoreApplication.translate("Pulses_calculator", u"Pulses_calculator", None))
        self.comboBox_var1.setItemText(0, QCoreApplication.translate("Pulses_calculator", u"MHz", None))
        self.comboBox_var1.setItemText(1, QCoreApplication.translate("Pulses_calculator", u"Hz", None))
        self.comboBox_var1.setItemText(2, QCoreApplication.translate("Pulses_calculator", u"kHz", None))
        self.comboBox_var1.setItemText(3, QCoreApplication.translate("Pulses_calculator", u"GHz", None))

        self.comboBox_var1.setCurrentText(QCoreApplication.translate("Pulses_calculator", u"MHz", None))
        self.label.setText(QCoreApplication.translate("Pulses_calculator", u"<-->", None))
        self.label_2.setText(QCoreApplication.translate("Pulses_calculator", u"<-->", None))
        self.pushButton_calculate.setText(QCoreApplication.translate("Pulses_calculator", u"Calculate", None))
        self.pushButton_cancel.setText(QCoreApplication.translate("Pulses_calculator", u"Cancel", None))
        self.label_4.setText(QCoreApplication.translate("Pulses_calculator", u"Seconds", None))
        self.radioButton_frequency.setText(QCoreApplication.translate("Pulses_calculator", u"Frequency", None))
        self.radioButton_pulses.setText(QCoreApplication.translate("Pulses_calculator", u"Pulses", None))
        self.comboBox_var3.setItemText(0, QCoreApplication.translate("Pulses_calculator", u"Hz", None))
        self.comboBox_var3.setItemText(1, QCoreApplication.translate("Pulses_calculator", u"kHz", None))
        self.comboBox_var3.setItemText(2, QCoreApplication.translate("Pulses_calculator", u"MHz", None))
        self.comboBox_var3.setItemText(3, QCoreApplication.translate("Pulses_calculator", u"GHz", None))

        self.comboBox_var2.setItemText(0, QCoreApplication.translate("Pulses_calculator", u"sec", None))
        self.comboBox_var2.setItemText(1, QCoreApplication.translate("Pulses_calculator", u"msec", None))
        self.comboBox_var2.setItemText(2, QCoreApplication.translate("Pulses_calculator", u"usec", None))
        self.comboBox_var2.setItemText(3, QCoreApplication.translate("Pulses_calculator", u"nsec", None))

        self.comboBox_var4.setItemText(0, QCoreApplication.translate("Pulses_calculator", u"sec", None))
        self.comboBox_var4.setItemText(1, QCoreApplication.translate("Pulses_calculator", u"msec", None))
        self.comboBox_var4.setItemText(2, QCoreApplication.translate("Pulses_calculator", u"usec", None))
        self.comboBox_var4.setItemText(3, QCoreApplication.translate("Pulses_calculator", u"nsec", None))

        self.label_binary_result.setText("")
        self.label_hexadecimal_result.setText("")
        self.label_error.setText("")
        self.pushButton_remove.setText(QCoreApplication.translate("Pulses_calculator", u"Remove all", None))
        self.pushButton_clean1.setText(QCoreApplication.translate("Pulses_calculator", u"clean", None))
        self.pushButton_clean3.setText(QCoreApplication.translate("Pulses_calculator", u"clean", None))
        self.pushButton_clean2.setText(QCoreApplication.translate("Pulses_calculator", u"clean", None))
        self.pushButton_clean4.setText(QCoreApplication.translate("Pulses_calculator", u"clean", None))
        self.pushButton_bin.setText(QCoreApplication.translate("Pulses_calculator", u"Bin", None))
        self.pushButton_hex.setText(QCoreApplication.translate("Pulses_calculator", u"Hex", None))
    # retranslateUi

